#  conditional routing: based on source labels
# A rule can indicate that it only applies to calls from workloads (pods) implementing the version v2 of the reviews service.
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - match:
    - sourceLabels:
        app: reviews
        version: v2