# fault injection: inserting delays: Fault injection is a testing method that introduces errors into a system to ensure that it
# can withstand and recover from error conditions.
# This example introduces a 5 second delay in 10% of the requests to the "v1" version of the ratings microservice.
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - fault:
      delay:
        percent: 10
        fixedDelay: 5s
    route:
    - destination:
      host: ratings
      subset: v1